### ISSUE TITLE
[Feature Request] Separate switch for the cpu-fan-memory script

### ISSUE THREAD

**Issue by yipinghuang1991** [nwg-piotr/tint2-executors#1]
I would like to see individual switchs to toggle each of the feature in cpu-fan-memory.
And if possible, the order of the arguments indicates the order or the readings.

**Comment by nwg-piotr** [comment]
Due to numerous changes, I re-wrote the script from scratch: [cpu-fan-mem.py](https://github.com/nwg-piotr/tint2-executors/blob/master/cpu-fan-mem.py). The old cpu-fan-memory.py script is now deprecated. Please find details in [Wiki](https://github.com/nwg-piotr/tint2-executors/wiki/CPU-load,-temperature,-fan-speed,-memory-usage).
